# Site Settings
title: UtodevBotnet v3
author: utodevbotnet
description: Инструмент для легального стресс-тестирования веб-сайтов
url: https://github.com/rnvntv/utodevddos
# Build Settings
theme: jekyll-theme-hacker
markdown: GFM
plugins:
  - jekyll-seo-tag
  - jemoji
